name: 'GitHub Issue Creator'
description: 'Create GitHub Ticket'
inputs:
  assignees:  # id of input
    description: 'A comma-separated list of assignees to the issue to be created'
    required: true
    # default: 'World'
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'build/index.js'
