name: Scheduled Tag Creation

on:
  schedule:
    # Refer to https://crontab.guru/
    - cron: '* 12 * * 6,0'
  workflow_dispatch:

jobs:
  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Name
        id: day-label
        run: |
          dayOfWeek=$(date +%u)
          day=$(case $dayOfWeek in
            6) echo "saturday" ;;
            7) echo "sunday" ;;
            *) echo "not-selected" ;;
          esac)

          echo "Day ${day}"

          days=(monday tuesday wednesday thursday friday saturday sunday)
          words=${days[$dayOfWeek - 1]}
          echo "::set-output name=day-in-words::$words"

      - name: List tags
        run: git tag --list

      - name: Create Fix Tag
        run: |
          tag=${{ steps.day-label.outputs.day-in-words}}
          if [ $(git tag --list "v${tag}") ]; then
            git push --delete origin "v${tag}"
          fi

          git tag -f -a "v${tag}" -m "Version ${tag}"
          git push origin "v${tag}"

      - name: Create Dynamic Tag
        run: |
          buildMetadata=`date '+%Y%m%d'`.sha.`git rev-parse --short HEAD`
          tag=latest+${buildMetadata}
          if [ $(git tag --list "v{$tag}") ]; then
            git push --delete origin "v${tag}"
          fi

          git tag -a "v${tag}" -m "Version ${tag}"
          git push -u origin "v${tag}"
