name: Auto-Builder

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Setup Git Config
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email '<>'

      - name: Create 
        run: |
          git tag -a vlatest+build -m 'Version latest+build'
          git push -u origin vlatest+build
