name: Auto-Builder

on:
  schedule:
    # Refer to https://crontab.guru/
    - cron: '*/5 * * * 6,0'

jobs:
  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com


      - name: Name
        id: day-label
        run: |
          dayOfWeek=$(date +%u)
          day=$(case $dayOfWeek in
            6) echo "saturday" ;;
            7) echo "sunday" ;;
            *) echo "not-selected" ;;
          esac)

          echo "Day ${day}"

          days=(monday tuesday wednesday thursday friday saturday sunday)
          echo "::set-output name=day-in-words::$($days[$dayOfWeek])"

      - name: Create Fix Tag
        run: |
          tag=${{ steps.day-label.outputs.day-in-words}}
          git tag -a v${tag} -m 'Version ${tag}'
          git push --delete origin ${tag}
          git push origin v${tag}

      - name: Create Dynamic Tag
        run: |
          buildMetadata=`date '+%Y%m%d'`.sha.`git rev-parse --short HEAD`
          git tag -a vlatest+${buildMetadata} -m 'Version latest+${buildMetadata}'
          git push -u origin vlatest+${buildMetadata}
#          git push --delete origin ${{ steps.day-label.outputs.day-in-words}}