name: Auto-Builder

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com


      - name: Name
        run: |
          dayOfWeek=$(date +%u)
          day=$(case $dayOfWeek in
            6) echo "saturday" ;;
            7) echo "sunday" ;;
            *) echo "not-selected" ;;
          esac)

          echo "Day ${day}"

      - name: Create 
        run: |
          buildMetadata=`date '+%Y%m%d'`.sha.`git rev-parse --short HEAD`
          git tag -a vlatest+${buildMetadata} -m 'Version latest+${buildMetadata}'
          git push -u origin vlatest+${buildMetadata}
