name: CI/CD v2

on:
  workflow_dispatch:
     inputs:
       environment:
         description: 'Environment'
         default: 'development'
         required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  transpile:
    name: Transpile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn package manager
        run: npm install -g yarn

      # - name: Install dependencies
      #   run: yarn

      # - name: Transpile Typescript to JavaScript
      #   run: yarn compile

      - name: Transpile Typescript to JavaScript
        run: echo "${{ github.event.inputs.environment }}"

  development:
    if: ${{ github.event.inputs.environment == 'development' }}
    name: Development
    runs-on: ubuntu-latest
    needs: transpile

    steps:
      - run: "echo Hello, World!"
    
  staging:
    if: ${{ github.event.inputs.environment == 'staging' }}
    name: Staging
    runs-on: ubuntu-latest
    needs: transpile

    steps:
      - run: "echo Hello, World!"


  production:
    if: ${{ github.event.inputs.environment == 'production' }}
    name: Production
    runs-on: ubuntu-latest
    needs: transpile

    steps:
      - run: "echo Hello, World!"