# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build, Publish Image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a single command using the runners shell
      - name: Install yarn package manager
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build binary
        run: yarn compile && yarn build

      - name: List contents
        run: ls -lash

      - name: Build & Publish Docker Image
        run: |
          branch=`git branch --show-current`
          tag=$(echo $branch | tr / _)
          docker build --tag ranskills/pipeline-test:$tag .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME}} --password-stdin
          docker push ranskills/pipeline-test:$tag


        