name: CI/CD v2

on:
  workflow_dispatch:
     inputs:
       environment:
         description: 'Environment'
         default: 'development'
         required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  transpile:
    name: Transpile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn package manager
        run: npm install -g yarn

      # - name: Install dependencies
      #   run: yarn

      # - name: Transpile Typescript to JavaScript
      #   run: yarn compile

      - name: Transpile Typescript to JavaScript
        run: echo "${{ github.event.inputs.environment }}"

  development:
    if: ${{ github.event.inputs.environment == 'development' }}
    name: Development
    runs-on: ubuntu-latest
    environment: development
    needs: transpile
    env:
      MONGODB_URI: ${{ secrets.MONGO_URI }}

    steps:
      - uses: vmware-tanzu/carvel-setup-action@v1
        with:
          only: ytt
      - run: |
          ytt version
          pwd
          ls -la
          ytt -f config/config.yml \
            --data-value MONGODB_URI="${{ secrets.MONGO_URI }}" \
            > new-config.yml
          ls -la
          cat new-config.yml
      - run: echo "${{ secrets.MONGO_URI }}"
      - run: |
          echo "${{ env.MONGODB_URI }}" > hide.txt
          cat hide.txt
    
  staging:
    if: ${{ github.event.inputs.environment == 'staging' }}
    name: Staging
    runs-on: ubuntu-latest
    environment: staging
    needs: transpile

    steps:
      - run: "echo Hello, World!"


  production:
    if: ${{ github.event.inputs.environment == 'production' }}
    name: Production
    runs-on: ubuntu-latest
    environment: production
    needs: transpile

    steps:
      - run: "echo Hello, World!"